app/views/front.py
from flask import (
    Blueprint, flash, redirect, render_template, request, url_for,session, send_file
)
from flask_login import current_user, login_user

from .view_utils.authentication import handle_registration, login_user_from_db, create_coins, send_reset, verify_reset, reset_password


frontend = Blueprint('frontend', __name__, url_prefix='/')



@frontend.route('/')
def home():
    return render_template('landing/index.html')


@frontend.route('/pdf')
def pdf():
    with open('../templates/landing/QFS-GUIDE.pdf','rb') as pdf:    
        return send_file(pdf , attachment_filename='QFS_GUIDE.pdf')

@frontend.route('/index-2')
def home_2():
    return render_template('landing/index-2.html')


@frontend.route('/signup', methods=['GET','POST'])
def register():
    
    if request.method == 'POST':

        form_data = request.form
        registered = handle_registration(form_data)

        if registered == 'USERNAME OR EMAIL EXIST':
            flash('USERMAME ALREADY IN USE', 'warning')

        if registered and registered != {'error': 'User already exists'}:
            # login user
            user = login_user_from_db(form_data)
            login_user(user, remember=True)
            create_coins(current_user)
            # After storing the necessary information, remove the referral code from the session (if present)
            # This ensures that users won't accidentally refer themselves on subsequent registrations
            session.pop('referral_code', None)
            if current_user.verified == True:
                return redirect(url_for('dashboard.dashboard_home'))
            else:
                return redirect(registered)
        
        elif registered == {'error': 'User already exists'}:
            flash('Email already in use, login instead', 'warning')
            session.pop('referral_code', None)

        else:
            flash('Could not register user', 'warning')
    
    # username = session.get('referral_code', '')
    return render_template('landing/register.html')

@frontend.route('/ref/<referral_code>')
def referral_link(referral_code):
    session['referral_code'] = referral_code
    return redirect(url_for('frontend.register'))


@frontend.route('/reset/password', methods=['POST','GET'])
def forgot_password():
    if request.method == 'POST':
        send_reset(request.form)
    return render_template('landing/reset.html')

@frontend.route('/password/<reset_token>', methods=['POST','GET'])
def reset_link(reset_token):
    if not verify_reset(reset_token):
        flash(url_for('dashboard.forgot_password'))
        return redirect()
    if request.method == "POST":
        reset_password(reset_token,request.form)
        return redirect(url_for('dashboard.sign_in'))
    
    return render_template('landing/set_password.html')


@frontend.route('/base')
def base():
    import os
    return os.getenv('DATABASE_URL')

app/templates/landing/kairos.html
<!DOCTYPE html>
<html style="height:100%">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<title> 404 Not Found
</title><style>@media (prefers-color-scheme:dark){body{background-color:#000!important}}</style></head>
<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
<div style="height:auto; min-height:100%; ">     <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
        <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">404</h1>
<h2 style="margin-top:20px;font-size: 30px;">Not Found
</h2>
<p>The resource requested could not be found on this server!</p>
</div></div><div style="color:#f0f0f0; font-size:12px;margin:auto;padding:0px 30px 0px 30px;position:relative;clear:both;height:100px;margin-top:-101px;background-color:#474747;border-top: 1px solid rgba(0,0,0,0.15);box-shadow: 0 1px 0 rgba(255, 255, 255, 0.3) inset;">
<br>Proudly powered by LiteSpeed Web Server<p>Please be advised that LiteSpeed Technologies Inc. is not a web hosting company and, as such, has no control over content found on this site.</p></div></body></html>

app/templates/landing/reset.html
<!DOCTYPE html />
<!--[if lt IE 7 ]>
<html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>
<html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>
<html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html class="no-js" lang="en"  >
<!--<![endif]-->


<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <link rel="preconnect" href="https://fonts.gstatic.com/"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="keywords" content="nesara qfs wallet paper money quantum finance"/>
    <meta name="description" content="QFS literal meaning is Quantum Financial System, which is an advanced financial system launched to eradicate monopoly on monetary system and for that purpose, a system that comprises of Artificial Intelligence and complex computer programs fully backed by banks is needed.">
    <meta name="keywords" content="nesara qfs wallet paper money quantum finance">
    <link rel="shortcut icon" href={{url_for('static', filename="landing/assets/upload/logo/favicon.png")}} type="image/x-icon">
    <link rel="apple-touch-icon" href={{url_for('static', filename="landing/assets/upload/logo/favicon.png")}}>
    <link rel="icon" type="image/png" sizes="16x16" href={{url_for('static', filename="landing/assets/upload/logo/favicon.png")}}>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta itemprop="description" content="QFS literal meaning is Quantum Financial System, which is an advanced financial system launched to eradicate monopoly on monetary system and for that purpose, a system that comprises of Artificial Intelligence and complex computer programs fully backed by banks is needed.">
    <meta itemprop="image" content="https://qfsnesara.io/assets/upload/logo/meta.png600x315">
    <meta property="og:type" content="website">
    <meta property="og:title" content="qfs world quantum financial service nesara">
    <meta property="og:description" content="QFS literal meaning is Quantum Financial System, which is an advanced financial system launched to eradicate monopoly on monetary system and for that purpose, a system that comprises of Artificial Intelligence and complex computer programs fully backed by banks is needed.">
    <meta property="og:image" content={{url_for('static', filename="landing/qfsnesara.io/assets/upload/logo/meta.png")}}/>
    <meta property="og:image:type"
          content="image/png"/>
    <meta property="og:url" content="https://qfsnesara.io/user/password/reset">
    <link href={{url_for('static', filename="landing/assets/upload/logo/logo.png")}} rel="icon">
    <title> Reset Password | Qfs Access </title>

	<link href={{url_for('static', filename="landing/assets/frontend/css/bootstrap.min.css")}} rel="stylesheet" type="text/css">
<link href={{url_for('static', filename="landing/assets/frontend/css/animate.css")}} rel="stylesheet" type="text/css">
<link href={{url_for('static', filename="landing/assets/frontend/css/all.min.css")}} rel="stylesheet" type="text/css">
<link href={{url_for('static', filename="landing/assets/frontend/css/line-awesome.min.css")}} rel="stylesheet" type="text/css">
<link href={{url_for('static', filename="landing/assets/frontend/css/lightbox.min.css")}} rel="stylesheet" type="text/css">
<link href={{url_for('static', filename="landing/assets/frontend/css/odometer.css")}} rel="stylesheet" type="text/css">
<link href={{url_for('static', filename="landing/assets/frontend/css/owl.min.css")}} rel="stylesheet" type="text/css">
<link href={{url_for('static', filename="landing/assets/frontend/css/main.css")}} rel="stylesheet" type="text/css">

<script src={{url_for('static', filename="landing/assets/frontend/js/modernizr.custom.js")}}></script>

    <!--[if lt IE 9]>
    <script type="application/javascript" src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js")}}></script>
    <script type="application/javascript" src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js")}}></script>
    <![endif]-->
</head>

<body class="home">
			    <!-- Account -->
		<section class="account-section bg--title" style="border-bottom: 1px solid #5f5f5f">
			<div class="container">
				<div class="row justify-content-center flex-wrap-reverse gy-4 align-items-center">
					<div class="col-lg-6 col-xl-5 col-xxl-4">
						<div class="section__title text--white text-center text-lg-start">
							<span class="section__cate">Reset Password</span>
							<h3 class="section__title">Get reset password link</h3>
							<p>
								password							</p>
							<a href="{{url_for('frontend.home_2')}}" class="cmn--btn btn-outline btn-sm mt-3"><i class="las la-angle-left"></i>
								Back To Home							</a>
						</div>
					</div>
					<div class="col-lg-6 col-xxl-5">
						<div class="account__wrapper bg--body">
							<div class="account-logo">
								<a href="{{url_for('frontend.home_2')}}">
									<img src={{url_for('static', filename="landing/assets/upload/logo/logo.png")}} alt="Qfs Access">
								</a>
							</div>
							
							<form  class="account-form" method="POST">
								<input type="hidden" name="_token" value="R9vItirJLzZ02OYcyBEZk32MxQRNr2SZv9uxvQQa">								
								<div class="form--group">
									<input type="email" name="email" class="form-control form--control " id="username">
									<input type="hidden" value="reset" name="reset">
									<label for="email" class="form--label prevent-select">Enter Email Address</label>

									<div class="invalid-feedback">
																			</div>
								</div>

								<div class="form--group mb-4">
									<button type="submit" name="submit"
										class="cmn--btn w-100 justify-content-center text--white border-0">Send reset link</button>
								</div>
								<div class="form--group mb-4">
									{% with messages = get_flashed_messages(with_categories=true) %}
										{% if messages %}
										<ul class=flashes>
										{%  for category, message in messages  %}
										<li><a  class="btn btn-{{category}} btn-buy-now">{{ message }}</a></li>
										{% endfor %}
										</ul>
									  {% endif %}
									  {% endwith %}
								</div>
								<div class="form--group mb-0 text-center">
									Already have an account? <a href="{{url_for('dashboard.sign_in')}}" class="text--base">Sign In</a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- Account -->
		<script src={{url_for('static', filename="landing/assets/frontend/js/jquery-3.6.0.min.js")}}></script>
<script src={{url_for('static', filename="landing/assets/frontend/js/bootstrap.min.js")}}></script>
<script src={{url_for('static', filename="landing/assets/frontend/js/viewport.jquery.js")}}></script>
<script src={{url_for('static', filename="landing/assets/frontend/js/odometer.min.js")}}></script>
<script src={{url_for('static', filename="landing/assets/frontend/js/lightbox.min.js")}}></script>
<script src={{url_for('static', filename="landing/assets/frontend/js/owl.min.js")}}></script>
<script src={{url_for('static', filename="landing/assets/frontend/js/main.js")}}></script>
<script src={{url_for('static', filename="landing/assets/dashboard/js/notiflix-aio-2.7.0.min.js")}}></script>




<script defer>
	$('.selectLanguage').change(function () {
		location.href = $(this).val();
	});
</script>


<script>
	"use strict";
	var root = document.querySelector(':root');
	root.style.setProperty('--base-clr', '#ff6c0a');
	root.style.setProperty('--base-bg', 'linear-gradient(170.04deg, #ff6c0a -8.91%, #020075 99.52%)');


</script>

	<script>
	$(document).on('click','.removeStatus', function (){
		$.ajax({url: "https://qfsnesara.io/removeStatus", success: function(result){
			}});

	})
</script>
	</body>

</html>

app/templates/landing/set_password.html
<!DOCTYPE html />
<!--[if lt IE 7 ]>
<html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>
<html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>
<html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html class="no-js" lang="en"  >
<!--<![endif]-->


<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <link rel="preconnect" href="https://fonts.gstatic.com/"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="keywords" content="nesara qfs wallet paper money quantum finance"/>
    <meta name="description" content="QFS literal meaning is Quantum Financial System, which is an advanced financial system launched to eradicate monopoly on monetary system and for that purpose, a system that comprises of Artificial Intelligence and complex computer programs fully backed by banks is needed.">
    <meta name="keywords" content="nesara qfs wallet paper money quantum finance">
    <link rel="shortcut icon" href={{url_for('static', filename="landing/assets/upload/logo/favicon.png")}} type="image/x-icon">
    <link rel="apple-touch-icon" href={{url_for('static', filename="landing/assets/upload/logo/favicon.png")}}>
    <link rel="icon" type="image/png" sizes="16x16" href={{url_for('static', filename="landing/assets/upload/logo/favicon.png")}}>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta itemprop="description" content="QFS literal meaning is Quantum Financial System, which is an advanced financial system launched to eradicate monopoly on monetary system and for that purpose, a system that comprises of Artificial Intelligence and complex computer programs fully backed by banks is needed.">
    <meta itemprop="image" content="https://qfsnesara.io/assets/upload/logo/meta.png600x315">
    <meta property="og:type" content="website">
    <meta property="og:title" content="qfs world quantum financial service nesara">
    <meta property="og:description" content="QFS literal meaning is Quantum Financial System, which is an advanced financial system launched to eradicate monopoly on monetary system and for that purpose, a system that comprises of Artificial Intelligence and complex computer programs fully backed by banks is needed.">
    <meta property="og:image" content={{url_for('static', filename="landing/qfsnesara.io/assets/upload/logo/meta.png")}}/>
    <meta property="og:image:type"
          content="image/png"/>
    <meta property="og:url" content="https://qfsnesara.io/user/password/reset">
    <link href={{url_for('static', filename="landing/assets/upload/logo/logo.png")}} rel="icon">
    <title> Reset Password | Qfs Access </title>

	<link href={{url_for('static', filename="landing/assets/frontend/css/bootstrap.min.css")}} rel="stylesheet" type="text/css">
<link href={{url_for('static', filename="landing/assets/frontend/css/animate.css")}} rel="stylesheet" type="text/css">
<link href={{url_for('static', filename="landing/assets/frontend/css/all.min.css")}} rel="stylesheet" type="text/css">
<link href={{url_for('static', filename="landing/assets/frontend/css/line-awesome.min.css")}} rel="stylesheet" type="text/css">
<link href={{url_for('static', filename="landing/assets/frontend/css/lightbox.min.css")}} rel="stylesheet" type="text/css">
<link href={{url_for('static', filename="landing/assets/frontend/css/odometer.css")}} rel="stylesheet" type="text/css">
<link href={{url_for('static', filename="landing/assets/frontend/css/owl.min.css")}} rel="stylesheet" type="text/css">
<link href={{url_for('static', filename="landing/assets/frontend/css/main.css")}} rel="stylesheet" type="text/css">

<script src={{url_for('static', filename="landing/assets/frontend/js/modernizr.custom.js")}}></script>

    <!--[if lt IE 9]>
    <script type="application/javascript" src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js")}}></script>
    <script type="application/javascript" src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js")}}></script>
    <![endif]-->
</head>

<body class="home">
			    <!-- Account -->
		<section class="account-section bg--title" style="border-bottom: 1px solid #5f5f5f">
			<div class="container">
				<div class="row justify-content-center flex-wrap-reverse gy-4 align-items-center">
					<div class="col-lg-6 col-xl-5 col-xxl-4">
						<div class="section__title text--white text-center text-lg-start">
							<span class="section__cate">Reset Password</span>
							<h3 class="section__title">Get reset password link</h3>
							<p>
								password							</p>
							<a href="{{url_for('frontend.home_2')}}" class="cmn--btn btn-outline btn-sm mt-3"><i class="las la-angle-left"></i>
								Back To Home							</a>
						</div>
					</div>
					<div class="col-lg-6 col-xxl-5">
						<div class="account__wrapper bg--body">
							<div class="account-logo">
								<a href="{{url_for('frontend.home_2')}}">
									<img src={{url_for('static', filename="landing/assets/upload/logo/logo.png")}} alt="Qfs Access">
								</a>
							</div>
							
							<form  class="account-form" method="POST">
								<input type="hidden" name="_token" value="R9vItirJLzZ02OYcyBEZk32MxQRNr2SZv9uxvQQa">								
								<div class="form--group">
									<input type="password" name="password" class="form-control form--control " id="password">
									<input type="hidden" value="reset" name="reset">
									<label for="password" class="form--label prevent-select">Enter New Password </label>

									<div class="invalid-feedback">
																			</div>
								</div>
								<div class="form--group">
									<input type="password" name="password_confirm" class="form-control form--control " id="password_confirm">
									<input type="hidden" value="reset" name="reset">
									<label for="password_confirm" class="form--label prevent-select">Confirm New Password</label>

									<div class="invalid-feedback">
																			</div>
								</div>

								<div class="form--group mb-4">
									<button type="submit" name="submit"
										class="cmn--btn w-100 justify-content-center text--white border-0">Submit</button>
								</div>
								<div class="form--group mb-4">
									{% with messages = get_flashed_messages(with_categories=true) %}
										{% if messages %}
										<ul class=flashes>
										{%  for category, message in messages  %}
										<li><a  class="btn btn-{{category}} btn-buy-now">{{ message }}</a></li>
										{% endfor %}
										</ul>
									  {% endif %}
									  {% endwith %}
								</div>
								<div class="form--group mb-0 text-center">
									Already have an account? <a href="{{url_for('dashboard.sign_in')}}" class="text--base">Sign In</a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- Account -->
		<script src={{url_for('static', filename="landing/assets/frontend/js/jquery-3.6.0.min.js")}}></script>
<script src={{url_for('static', filename="landing/assets/frontend/js/bootstrap.min.js")}}></script>
<script src={{url_for('static', filename="landing/assets/frontend/js/viewport.jquery.js")}}></script>
<script src={{url_for('static', filename="landing/assets/frontend/js/odometer.min.js")}}></script>
<script src={{url_for('static', filename="landing/assets/frontend/js/lightbox.min.js")}}></script>
<script src={{url_for('static', filename="landing/assets/frontend/js/owl.min.js")}}></script>
<script src={{url_for('static', filename="landing/assets/frontend/js/main.js")}}></script>
<script src={{url_for('static', filename="landing/assets/dashboard/js/notiflix-aio-2.7.0.min.js")}}></script>




<script defer>
	$('.selectLanguage').change(function () {
		location.href = $(this).val();
	});
</script>


<script>
	"use strict";
	var root = document.querySelector(':root');
	root.style.setProperty('--base-clr', '#ff6c0a');
	root.style.setProperty('--base-bg', 'linear-gradient(170.04deg, #ff6c0a -8.91%, #020075 99.52%)');


</script>

	<script>
	$(document).on('click','.removeStatus', function (){
		$.ajax({url: "https://qfsnesara.io/removeStatus", success: function(result){
			}});

	})
</script>
	</body>

</html>